# Generated by Django 4.0.6 on 2024-09-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinematicket', '0008_alter_food_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cinematicket.food', verbose_name='غذا'),
        ),
    ]
